
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#bluetooth:



# Load personalized files (!include_dir_merge_list customize/)
command_line: !include customize/command_line.yaml

template: !include customize/templete-cmd_line.yaml


# Example configuration.yaml entry
sensor:
  - platform: temper
    name: TEMPer USBdevice
    offset: 0             # Opcional: Ajuste de valor
    scale: 1              # Opcional: Escala do sensor


